### ISSUE TITLE
Multiple random postings from Strava

### ISSUE THREAD

**Issue by robert-will-brown** [dblock/slack-strava#102]
Hi we installed today, but are being spammed multiple times with random runs / rides that we've historically done.  Can you advise?

![image](https://user-images.githubusercontent.com/7024743/98170087-4e018a80-1ee5-11eb-8be3-5eb18d9ccb79.png)

Regards,

**Comment by dblock** [comment]
These seem to come from a connected club. How old are these posts? drop me an email and i can help with the unexpected ones

**Comment by dblock** [comment]
Flush out prior activities on first club sync, https://github.com/dblock/slack-strava/commit/6dc9325450e27dfda05cfb5db42c825209d61860.
