### ISSUE TITLE
Display units of measure optionally in metric or in imperial units and temperature in Celsius or Fahrenheit

### ISSUE THREAD

**Issue by lukwlodarczyk** [dblock/slack-strava#105]
Hi, 
It would be great to ease usage for users outside of imperial unit system.
BTW This is great app used also in Europe ;)

**Comment by dblock** [comment]
You can change <b>units</b> with <b>set units mi</b> (imperial, default), <b>set units km</b> (metric) or <b>set units both</b> to display both values.
