### ISSUE TITLE
DM indicating server error

### ISSUE THREAD

**Issue by msoupcoff** [dblock/slack-strava#111]
When DMing Slava bot (ex: help, info, etc), getting "No primary server is available in cluster: #<Cluster topology=Single[dokku-mongo-strava-bot:27017] servers=[#<Server address=dokku-mongo-strava-bot:27017 UNKNOWN pool=#<ConnectionPool size=0 (0-5) used=0 avail=0 pending=0>>]> with timeout=30, LT=0.015"

![Slava](https://user-images.githubusercontent.com/1220785/112510931-50676280-8d68-11eb-8c51-40d411728a2a.png)

**Comment by dblock** [comment]
This was resolved, apologies.
