### ISSUE TITLE
Maps not showing for club activities

### ISSUE THREAD

**Issue by clefebvre** [dblock/slack-strava#149]
Hi @dblock,

Many thanks for this awesome bot!

Are maps only supposed to show up for account activities? or also for club activities?

In our slack none of us registered our personal strava activity with the bot. Instead, we set up two clubs (one for cycling, one for walks/running/hiking) and added these to slava.

We don't see any maps though.. 

Here are some screenshots in case this helps:

![image](https://user-images.githubusercontent.com/1138515/224101822-818663ea-2b7f-45e7-a4de-3e95ce3accb1.png)

and in our channel:

![image](https://user-images.githubusercontent.com/1138515/224101970-b2c76aac-5812-41aa-84c4-9589063362f2.png)

![image](https://user-images.githubusercontent.com/1138515/224102040-cbacbf38-1f8a-445a-975f-3f587ff47478.png)

**Comment by dblock** [comment]
Unfortunately Strava does not return map information for club activities (or much useful information, really). If users do connect their strava accounts, then Slava is smart enough to merge a club activity and a personal user activity, and you will see maps for those. That's the best we can do, I'll close this.
