### ISSUE TITLE
Expired subscriptions can't be reactivated

### ISSUE THREAD

**Issue by anbugge** [dblock/slack-strava#155]
I got a message about my subscription being expired, probably as a result of the recent commit. (Seems like I haven't paid since I first subscribed years ago, so no problem there).

But I can't reactivate the subscription. When I try to "Pay $9.99 by card", I just get a message "Customer Already Registered".

**Comment by brunofracalossi** [comment]
+1 facing this bug to renew a subscritpion

**Comment by dblock** [comment]
This will also happen if your subscription expired. If anyone is facing this issue with a hosted bot on playplay.io, please email me dblock at vestris dot com.

**Comment by dblock** [comment]
Fixed in https://github.com/dblock/slack-strava/commit/475cff185f3f364885ea97d7377cc5969afd7d95.
