### ISSUE TITLE
Ask the user whether to post private activities after connecting

### ISSUE THREAD

**Issue by dblock** [dblock/slack-strava#47]
From https://github.com/dblock/slack-strava/issues/35#issuecomment-407418345

**Comment by petewilcock** [comment]
Thanks for this, I think this is a sensible solution :) Will definitely be purchasing this!

**Comment by dblock** [comment]
Thanks @petewilcock! The money goes to [the Team for Kids charity](https://runwithtfk.org/Profile/PublicPage/61018), at least *someone* cares about the children :)

**Comment by dblock** [comment]
In https://github.com/dblock/slack-strava/commit/79b0ba345a3701ae24eebd4676401d32d7aa3552 we now tell the user about private activities and explain how to toggle that.
