### ISSUE TITLE
(Re)post a specific activity 

### ISSUE THREAD

**Issue by dblock** [dblock/slack-strava#63]
I tried to share a Strava activity directly into a slack channel last night and it failed spectacularly (so I found slava :) )  Would love to have shared a couple key historical activities to introduce Strava to my new company... I DON'T want all of my 5y history to flow in <ick>. Feature might be: /slava get rides on 2018-12-15 (if 1, post it, if >1 make list and pick 1.  --> maybe an edge case ask.

**Comment by stonematt** [comment]
Occasionally we get to add a brag-worthy ride to our history, and a year from now, I might throw it into a discussion.  

This would be pretty slick.

**Comment by dblock** [comment]
I think slack-strava should unfurl Strava links, https://github.com/dblock/slack-strava/issues/64

**Comment by dblock** [comment]
Closed via #64

**Comment by dblock** [comment]
@stonematt Unfurling does what you want for your own activities. You'll need to re-authorize the new permission scopes (go to https://slava.playplay.io/ and click add to slack without uninstalling the bot, ignore that it tells you that the bot is already registered). 

Pasting an activity into any channel that belongs to you will unfurl it as long as your slack account is connected to strava.
