### ISSUE TITLE
long ride not showing up in channel

### ISSUE THREAD

**Issue by dmca-faire** [dblock/slack-strava#85]
My last 2 big rides didn't show up on our channel. I manually checked and all other rides posted in our Strava group were synced to the slack channel. My other, shorter rides were also synced. I am wondering if this has anything to do with the size of the ride file.

https://www.strava.com/activities/3286118305
https://www.strava.com/activities/3318422565

**Comment by dblock** [comment]
What's your Slack team and username or athlete id (if you click on your picture in strava it will be in the URL)? Feel free to email me dblock at dblock dot org if you don't want to post here.

**Comment by dblock** [comment]
Looks like we're missing activities. Likely because a single sync is [asking for 10 latest](https://github.com/dblock/slack-strava/blob/a14c5f5bd59cbf43cdefe84862ed588c75181e6d/slack-strava/models/club.rb#L118).

Catch up script, found at least two dozen across all clubs:

```ruby
Club.connected_to_strava.each do |club|
  begin
    puts club.to_s
    current_page = 1
    while current_page < 3
      club.strava_client.club_activities(club.strava_id, page: current_page, per_page: 10).each do |activity|
        begin
          next if Activity.where(
            name: activity.name,
            distance: activity.distance, 
            moving_time: activity.moving_time, 
            elapsed_time: activity.elapsed_time, 
            total_elevation_gain: activity.total_elevation_gain
          ).exists?

          puts "#{activity.name}: missing"

          club_activity = ClubActivity.new(ClubActivity.attrs_from_strava(activity).merge(team: club.team, club: club))
          next if ClubActivity.where(strava_id: club_activity.strava_id).exists?
          club_activity.save!
        rescue Exception => e
          puts e.message
        end
      end
      current_page += 1
    end
  rescue Exception => e
    puts e.message
  end
end
```

**Comment by dblock** [comment]
I believe I have fixed this @dmca-faire, thank you for reporting it. Please do let me know if this happens again.

**Comment by dblock** [comment]
For future debugging: user id = 5e1523da0a005e010235b3de, club id = 5e1524210a005e010235b3ec

**Comment by dmca-faire** [comment]
Thanks, @dblock!
