### ISSUE TITLE
Maps aren't showing, both full/thumbs

### ISSUE THREAD

**Issue by igordebatur** [dblock/slack-strava#96]
The screenshots are attached.

![slack_bP0D4ky3Sk](https://user-images.githubusercontent.com/524055/86107108-19f70280-baca-11ea-9dbe-0ee2fad93994.png)
![slack_yblAOU7Sk4](https://user-images.githubusercontent.com/524055/86107117-1bc0c600-baca-11ea-9cd7-9645b00378e1.png)

**Comment by dblock** [comment]
This was reported before on some Slacks, and seems to be something with Slack itself or possibly a team configuration. Was not able to find what it is, see #3. Had reached out to Slack about this and wasn't able to get anything conclusive.

This is what the bot posts:

```
{"attachments":[{"fallback":"Morning Ride via \u003c@U9550BZ9N\u003e, 9.69km 35m37s 3m41s/km","title":"Morning Ride","title_link":"https://www.strava.com/activities/3691708182","text":"\u003c@rsedykh171\u003e on Tuesday, June 30, 2020 at 10:34 AM","image_url":"https://slava.playplay.io/api/maps/5efaff3d934594010993ba24.png","fields":[{"title":"Type","value":"Ride 🚴","short":true},{"title":"Distance","value":"9.69km","short":true},{"title":"Moving Time","value":"35m37s","short":true},{"title":"Elapsed Time","value":"1h25m33s","short":true},{"title":"Pace","value":"3m41s/km","short":true},{"title":"Speed","value":"16.3km/h","short":true},{"title":"Elevation","value":"94.1m","short":true},{"title":"Max Speed","value":"63.0km/h","short":true},{"title":"Weather","value":"21°C Rain","short":true}],"author_name":"Roman Sedykh","author_link":"https://www.strava.com/athletes/roman_sedykh","author_icon":"https://graph.facebook.com/10157224345431795/picture?height=256\u0026width=256"}],"channel":"C0159LUJNBG","as_user":true}
``` 

You can see that the map is in there.

![](https://slava.playplay.io/api/maps/5efaff3d934594010993ba24.png)

**Comment by dblock** [comment]
Also check out [message builder](https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22fallback%22%3A%22Morning%20Ride%20via%20%3C%40U9550BZ9N%3E%2C%209.69km%2035m37s%203m41s%2Fkm%22%2C%22title%22%3A%22Morning%20Ride%22%2C%22title_link%22%3A%22https%3A%2F%2Fwww.strava.com%2Factivities%2F3691708182%22%2C%22text%22%3A%22%3C%40rsedykh171%3E%20on%20Tuesday%2C%20June%2030%2C%202020%20at%2010%3A34%20AM%22%2C%22image_url%22%3A%22https%3A%2F%2Fslava.playplay.io%2Fapi%2Fmaps%2F5efaff3d934594010993ba24.png%22%2C%22fields%22%3A%5B%7B%22title%22%3A%22Type%22%2C%22value%22%3A%22Ride%20%F0%9F%9A%B4%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Distance%22%2C%22value%22%3A%229.69km%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Moving%20Time%22%2C%22value%22%3A%2235m37s%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Elapsed%20Time%22%2C%22value%22%3A%221h25m33s%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Pace%22%2C%22value%22%3A%223m41s%2Fkm%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Speed%22%2C%22value%22%3A%2216.3km%2Fh%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Elevation%22%2C%22value%22%3A%2294.1m%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Max%20Speed%22%2C%22value%22%3A%2263.0km%2Fh%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Weather%22%2C%22value%22%3A%2221%C2%B0C%20Rain%22%2C%22short%22%3Atrue%7D%5D%2C%22author_name%22%3A%22Roman%20Sedykh%22%2C%22author_link%22%3A%22https%3A%2F%2Fwww.strava.com%2Fathletes%2Froman_sedykh%22%2C%22author_icon%22%3A%22https%3A%2F%2Fgraph.facebook.com%2F10157224345431795%2Fpicture%3Fheight%3D256%26width%3D256%22%7D%5D%2C%22channel%22%3A%22C0159LUJNBG%22%7D) that renders this correctly.

<img width="551" alt="Screen Shot 2020-06-30 at 9 17 19 AM" src="https://user-images.githubusercontent.com/542335/86130692-86660780-bab2-11ea-84b8-5a87f9ef174a.png">

**Comment by dblock** [comment]
I opened another support request, https://dblockdotorg.slack.com/help/requests/2973315

**Comment by dblock** [comment]
@igordebatur Slack advises to first check whether the URLs are blocked, https://slack.com/help/articles/360001502048-Manage-link-previews-for-your-workspace#view-a-list-of-blocked-previews

Is there a channel I can send lots of messages to? The other thing they are suggesting is to send a whole load (1 per second for a long time) and see if any render at all or whether it's consistently none.

**Comment by igordebatur** [comment]
I checked, none of potentially relevant URLs are blocked:
<img width="891" alt="Screenshot 2020-07-01 at 11 53 41" src="https://user-images.githubusercontent.com/524055/86224722-ea133200-bb91-11ea-9581-33b609ac5a92.png">

I created the "test-slava" channel and invited @slava , you can send any number of messages there, thx!

**Comment by Slava** [comment]
I can't express how much frustration the naming of this chat bot brought to me in my work, and now GitHub notifications.

**Comment by dblock** [comment]
> I can't express how much frustration the naming of this chat bot brought to me in my work, and now GitHub notifications.

😢 сори

I wish Slack allowed renaming bots in teams or Strava allowed to create a bot with "strava" in the name.

**Comment by Slava** [comment]
@dblock all good, my coworkers had a lot of fun with the bot. I got accidentally tagged in some of the runners/bikers channels but it is not as bad as my first comment might have made it seem.

![image](https://user-images.githubusercontent.com/2608446/86285598-bfc57280-bb99-11ea-9bf9-8aed6d1931d8.png)

**Comment by dblock** [comment]
> @dblock all good, my coworkers had a lot of fun with the bot. I got accidentally tagged in some of the runners/bikers channels but it is not as bad as my first comment might have made it seem.
> 
> ![image](https://user-images.githubusercontent.com/2608446/86285598-bfc57280-bb99-11ea-9bf9-8aed6d1931d8.png)

Haha, can I post this on Twitter or RT someone?

**Comment by dblock** [comment]
This one rendered:

```
I, [2020-07-06T17:04:38.637212 #18808]  INFO -- : Skipping user_id=U02BWGK6S, user_name=dm, name=Afternoon Ride , date=Monday, July 06, 2020 at 05:51 PM, distance=30.22km, moving time=1h10s, pace=1m59s/km, proxy=https://slava.playplay.io/api/maps/5f0359a693459449782f8526.png, png=109197 byte(s), private.
I, [2020-07-06T17:08:25.177402 #18808]  INFO -- : Rebragging about user_id=U02BWGK6S, user_name=dm, name=Afternoon Ride , date=Monday, July 06, 2020 at 05:51 PM, distance=30.22km, moving time=1h10s, pace=1m59s/km, proxy=https://slava.playplay.io/api/maps/5f0359a693459449782f8526.png, png=109197 byte(s).
I, [2020-07-06T17:18:47.138117 #18808]  INFO -- : Bragging about user_id=U02BWGK6S, user_name=dm, name=Afternoon Workout, date=Monday, July 06, 2020 at 05:51 PM, distance=30.22km, moving time=1h10s, pace=1m59s/km, proxy=https://slava.playplay.io/api/maps/5f0359a693459449782f8526.png, png=109197 byte(s).
I, [2020-07-06T17:18:47.340238 #18808]  INFO -- : Posting '{"attachments":[{"fallback":"Afternoon Workout via \u003c@U02BWGK6S\u003e, 30.22km 1h10s 1m59s/km","title":"Afternoon Workout","title_link":"https://www.strava.com/activities/3722702171","text":"\u003c@dm\u003e on Monday, July 06, 2020 at 05:51 PM\n\nPartly Cloudy, 17°C, Feels like 17°C, Humidity 64%, Wind 6m/s from WNW - by Klimat.app","image_url":"https://slava.playplay.io/api/maps/5f0359a693459449782f8526.png","fields":[{"title":"Type","value":"Ride 🚴","short":true},{"title":"Distance","value":"30.22km","short":true},{"title":"Moving Time","value":"1h10s","short":true},{"title":"Elapsed Time","value":"1h5m31s","short":true},{"title":"Pace","value":"1m59s/km","short":true},{"title":"Speed","value":"30.1km/h","short":true},{"title":"Elevation","value":"29m","short":true},{"title":"Max Speed","value":"38.9km/h","short":true},{"title":"Heart Rate","value":"149.7bpm","short":true},{"title":"Max Heart Rate","value":"172.0bpm","short":true},{"title":"PR Count","value":"13","short":true},{"title":"Weather","value":"16°C Clouds","short":true}],"author_name":"Dmitry Mukhin","author_link":"https://www.strava.com/athletes/dmukhin","author_icon":"https://lh3.googleusercontent.com/a-/AOh14Gi35Obte0OWZZDBoiqf0L5yMtVJBDLHM-vO1wq5z-k"}],"channel":"C0159LUJNBG","as_user":true}' to name=Uploadcare, id=T02BWGAM4 on #cycling.
D, [2020-07-06T17:18:58.506243 #18808] DEBUG -- : Getting map ID 5f0359a693459449782f8526.
D, [2020-07-06T17:18:58.646541 #18808] DEBUG -- : Found activity ID 5f0359a693459449782f8526 with URL https://slava.playplay.io/api/maps/5f0359a693459449782f8526.png.
D, [2020-07-06T17:18:58.647022 #18808] DEBUG -- : Returning 109197 byte(s) of PNG for activity ID 5f0359a693459449782f8526.
I, [2020-07-06T19:56:17.790508 #18808]  INFO -- : Rebragging about user_id=U02BWGK6S, user_name=dm, name=Afternoon Workout, date=Monday, July 06, 2020 at 05:51 PM, distance=30.22km, moving time=1h10s, pace=1m59s/km, proxy=https://slava.playplay.io/api/maps/5f0359a693459449782f8526.png, png=109197 byte(s).
I, [2020-07-06T19:56:17.794496 #18808]  INFO -- : Updating '{"attachments":[{"fallback":"Afternoon Workout via \u003c@U02BWGK6S\u003e, 30.22km 1h10s 1m59s/km","title":"Afternoon Workout","title_link":"https://www.strava.com/activities/3722702171","text":"\u003c@dm\u003e on Monday, July 06, 2020 at 05:51 PM\n\nPartly Cloudy, 17°C, Feels like 17°C, Humidity 64%, Wind 6m/s from WNW - by Klimat.app\r\n-- myWindsock Report --\r\nWeather Impact: 4.3%\r\nHeadwind: 53% @ 5.6-9.6m/s\r\nLongest Headwind: 11m 22s\r\nAir Speed: 30.7km/h\r\nTemp: 16.8-16.9°C\r\nPrecip: 8% @ 0.11 Inch/hr\r\n-- END --","image_url":"https://slava.playplay.io/api/maps/5f0359a693459449782f8526.png","fields":[{"title":"Type","value":"Ride 🚴","short":true},{"title":"Distance","value":"30.22km","short":true},{"title":"Moving Time","value":"1h10s","short":true},{"title":"Elapsed Time","value":"1h5m31s","short":true},{"title":"Pace","value":"1m59s/km","short":true},{"title":"Speed","value":"30.1km/h","short":true},{"title":"Elevation","value":"29m","short":true},{"title":"Max Speed","value":"38.9km/h","short":true},{"title":"Heart Rate","value":"149.7bpm","short":true},{"title":"Max Heart Rate","value":"172.0bpm","short":true},{"title":"PR Count","value":"13","short":true},{"title":"Weather","value":"16°C Clouds","short":true}],"author_name":"Dmitry Mukhin","author_link":"https://www.strava.com/athletes/dmukhin","author_icon":"https://lh3.googleusercontent.com/a-/AOh14Gi35Obte0OWZZDBoiqf0L5yMtVJBDLHM-vO1wq5z-k"}],"channel":"C0159LUJNBG","ts":"1594055938.046000","as_user":true}' to name=Uploadcare, id=T02BWGAM4 on #C0159LUJNBG.
D, [2020-07-06T19:56:17.923132 #18808] DEBUG -- : Getting map ID 5f0359a693459449782f8526.
D, [2020-07-06T19:56:18.078480 #18808] DEBUG -- : Found activity ID 5f0359a693459449782f8526 with URL https://slava.playplay.io/api/maps/5f0359a693459449782f8526.png.
D, [2020-07-06T19:56:18.078705 #18808] DEBUG -- : Returning 109197 byte(s) of PNG for activity ID 5f0359a693459449782f8526.
```

**Comment by dblock** [comment]
Added index to `map._id` in https://github.com/dblock/slack-strava/commit/eaff25c5e6e8bae63fa8100fb6adcc47bb14b596

**Comment by dblock** [comment]
I was able to reproduce on a personal test Slack.

1) First chat_postMessage did not render the image. I see a request from Slackbot 1.0 (+https://api.slack.com/robots) a few ms after the post though that returned the PNG. The PNG is cached and is definitely correct.

2) At some point I see a request from Slack-ImgProxy (+https://api.slack.com/robots).

2) Subsequent chat_postMessage rendered the image (screenshot, second post). Same robots request.

3) A chat_update to the message without any changes re-renders the image in the original post. Same robots request.

**Comment by dblock** [comment]
Looks like swapping Puma for Unicorn resolved this? 
https://github.com/dblock/slack-strava/commit/207f1a215032a81097b5c01488cfc03fe3832193

**Comment by dblock** [comment]
In https://github.com/dblock/slack-strava/commit/949c96b69092af728b58700ab234e7f91b48819d and https://github.com/dblock/slack-strava/commit/1325e727891a38f4f27d84d065904df7af380d00 I added a bool to re-experiment with a redirect to a map. It has been a few months without problems, today all teams in production were set to have `proxy_maps = false`. If you have a map problem please comment on this issue.
